# Generated by Django 3.0.7 on 2020-06-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinbasket_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='is_active',
        ),
    ]
