# Generated by Django 3.0.7 on 2020-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_productinbasket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
